(load "general-setup")
(load "improved-scrolling")
(load "tramp-setup")
(load "bindings")
(load "ibuffer-setup")
;; TODO: has to be tested!
(load "tabs-setup")
(load "compilation")
(load "git-setup")
(load "cxx-setup")
(load "gnuplot-setup")
(load "yas-setup")
(load "org-mode-setup")
(load "latex-related-setup")
(load "ack-setup")
