(load "general-setup")
(load "bindings")
(load "theme")
(load "mac-friend")
(load "clock-setup")
;; (load "improved-scrolling")
(load "tramp-setup")
(load "ibuffer-setup")
;; TODO: has to be tested!
(load "tabs-setup")
(load "ido-setup")
(load "compilation")
(load "git-setup")
(load "cxx-setup")
(load "gnuplot-setup")
(load "yas-setup")
(load "org-mode-setup")
(load "latex-related-setup")
(load "ack-setup")
(load "dot-lang-setup")
(load "cmake-setup")
